apiVersion: v1
kind: Pod
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  volumes:
    - name: ${DB_ACCESS_SA}-volume
      secret:
        secretName: ${DB_ACCESS_SA}-secret
  restartPolicy: OnFailure
  containers:
    - image: dpage/pgadmin4
      name: pgadmin4
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@mail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: postgres
      ports:
        - containerPort: 80
          name: pgadmin4
    - name: cloud-sql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.17
      env:
        - name: PROJECT
          value: ${PROJECT}
        - name: REGION
          value: ${REGION}
        - name: DB_INSTANCE
          value: ${DB_INSTANCE}
      command:
        - "/cloud_sql_proxy"
        - "-ip_address_types=PRIVATE"
        - "-instances=${PROJECT}:${REGION}:${DB_INSTANCE}=tcp:5432"
        - "-credential_file=/secrets/credentials.json"
      volumeMounts:
        - name: ${DB_ACCESS_SA}-volume
          mountPath: /secrets/
          readOnly: true
